pgsql_azure_olist:
    user:       postgres
    password:   
    host:       localhost
    port:       5432
    type:       postgresql
    db_name:    olist_TAS
    docker_host:  localhost


mysql_datalab:
    user:       root
    password:   greta2023
    host:       localhost
    port:       3306
    type:       mysql
    db_name:    g5

pgsql_datalab:
    user:       medjahed
    password:   64234a746dd79d81ba42ceae31b88e6f681cae16dd17a1b9339671043e28ad76
    host:       localhost
    port:       5432
    type:       postgresql
    db_name:    olist_TAS
    docker_host:  localhost

ssh_tunnel-azure:
    user:       greta2023
    password:   DyzGWL5UFvCvjup
    host:       olist-tas-grp3.francecentral.cloudapp.azure.com
    port:       22

ssh_tunnel_datalab:
    user:       medjahed
    password:   64234a746dd79d81ba42ceae31b88e6f681cae16dd17a1b9339671043e28ad76
    host:       datalab.myconnectech.fr
    port:       22

ssh_tunnel_datalab_mame:
    user:       medjahed
    password:   64234a746dd79d81ba42ceae31b88e6f681cae16dd17a1b9339671043e28ad76
    host:       datalab-mame.myconnectech.fr
    port:       22